use std::fmt::Write as _;

fn main() {
    tauri_build::build();

    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let core_dir = format!("{}/../../sunshine_core", manifest_dir);

    cc::Build::new()
        .files([
            format!("{}/src/utils.c",        core_dir),
            format!("{}/src/kalman.c",       core_dir),
            format!("{}/src/mag_heading.c",  core_dir),
            format!("{}/src/control.c",      core_dir),
            format!("{}/src/brain.c",        core_dir),
        ])
        .include(format!("{}/include", core_dir))
        .flag_if_supported("-lm")
        .compile("sunshine_core");

    generate_core_constants(&core_dir);

    println!("cargo:rerun-if-changed={}/src", core_dir);
    println!("cargo:rerun-if-changed={}/include", core_dir);
}

/// Parse the numeric `#define`s out of sunshine_core.h and emit them as Rust
/// `pub const NAME: f64` into OUT_DIR/core_constants.rs. This is what makes the
/// header the single source of truth for per-robot constants: simulation.rs
/// includes the generated file instead of carrying hand-synced copies.
///
/// Handled: int/float literals with C `f`/`U` suffixes, simple arithmetic
/// expressions (e.g. `(16.0f * 3.14159265f)`), and references to previously
/// defined names (e.g. `DSHOT_MAX`) — all valid Rust once suffixes are
/// stripped. Anything else (function-like macros, strings) is skipped.
fn generate_core_constants(core_dir: &str) {
    let header = std::fs::read_to_string(format!("{}/include/sunshine_core.h", core_dir))
        .expect("read sunshine_core.h");
    let out_dir = std::env::var("OUT_DIR").unwrap();

    let mut out = String::from(
        "// AUTO-GENERATED by build.rs from sunshine_core/include/sunshine_core.h.\n\
         // Do not edit — change the header instead.\n",
    );
    let mut names: Vec<String> = Vec::new();

    for line in header.lines() {
        let Some(rest) = line.trim_start().strip_prefix("#define") else { continue };
        let rest = rest.trim_start();
        let Some((name, value)) = rest.split_once(char::is_whitespace) else { continue };
        if !name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') || name.contains('(') {
            continue; // function-like macro or junk
        }
        // Strip trailing comment.
        let value = value.split("/*").next().unwrap().split("//").next().unwrap().trim();
        if value.is_empty() { continue; }

        // Strip C numeric suffixes: `f`/`F` and `u`/`U` directly after a digit or '.'.
        let mut expr = String::with_capacity(value.len());
        let chars: Vec<char> = value.chars().collect();
        for (i, &c) in chars.iter().enumerate() {
            let after_num = i > 0 && (chars[i - 1].is_ascii_digit() || chars[i - 1] == '.');
            let ends_token = chars.get(i + 1).map_or(true, |n| !n.is_ascii_alphanumeric() && *n != '_');
            if after_num && ends_token && matches!(c, 'f' | 'F' | 'u' | 'U') {
                continue;
            }
            expr.push(c);
        }

        // Only emit expressions made of numbers, arithmetic, and known names.
        let ok = !expr.is_empty()
            && expr.chars().all(|c| {
                c.is_ascii_alphanumeric() || c == '_' || c == '.' || c == '(' || c == ')'
                    || c == '+' || c == '-' || c == '*' || c == '/' || c == ' '
            })
            && expr
                .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_' || c == '.'))
                .filter(|t| !t.is_empty())
                .all(|t| {
                    t.chars().next().unwrap().is_ascii_digit()
                        || t.starts_with('.')
                        || names.iter().any(|n| n == t)
                });
        if !ok { continue; }

        // `X as f64` promotes int literals and name references alike.
        writeln!(out, "pub const {}: f64 = ({}) as f64;", name, expr).unwrap();
        names.push(name.to_string());
    }

    assert!(
        names.iter().any(|n| n == "WHEEL_RADIUS_M") && names.iter().any(|n| n == "ROBOT_MASS_KG"),
        "core_constants codegen failed to parse expected constants from sunshine_core.h"
    );
    std::fs::write(format!("{}/core_constants.rs", out_dir), out).expect("write core_constants.rs");
}
