[env_base]
platform    = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board       = esp32-s3-devkitc-1
framework   = arduino
monitor_speed  = 921600
upload_speed   = 921600
build_flags    =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=0
lib_deps =
    adafruit/Adafruit ADXL375 @ ^1.0.0
    adafruit/Adafruit LIS3MDL @ ^1.2.0
    derdoktor667/DShotRMT @ ^0.9.5

[env:bringup_1_sensors]
extends    = env_base
build_flags = ${env_base.build_flags} -DBRINGUP_LEVEL=1

[env:bringup_2_dshot]
extends    = env_base
build_flags = ${env_base.build_flags} -DBRINGUP_LEVEL=2

[env:bringup_3_telemetry]
extends    = env_base
build_flags = ${env_base.build_flags} -DBRINGUP_LEVEL=3

[env:bringup_4_navigation]
extends    = env_base
build_flags = ${env_base.build_flags} -DBRINGUP_LEVEL=4

[env:production]
extends    = env_base
build_flags = ${env_base.build_flags} -DBRINGUP_LEVEL=0
