#!/usr/bin/env python3
"""Generate 4th-order LP Butterworth coefficients, fc=1 Hz, fs=1000 Hz.

Produces balanced biquad sections where each section has DC gain = 1.
Run from the project root. Requires scipy.
"""
import math
import numpy as np
from scipy.signal import butter

fc = 1.0
fs = 1000.0

# Get zeros, poles, gain from scipy
from scipy.signal import butter
z, p, k = butter(4, fc / (fs / 2.0), btype='low', output='zpk')

# Group poles into conjugate pairs; each biquad section gets one pair.
# All zeros are at z = -1 (from bilinear transform of s-domain zeros at infinity).
# Distribute gain evenly: each section gets k^(1/n_sections).
n_sections = len(p) // 2  # 2 sections for order-4
k_per_section = k ** (1.0 / n_sections)

# Sort poles by imag part ascending so pairing is deterministic
poles_sorted = sorted(p, key=lambda x: abs(x.imag))
sections = []
used = set()
for i, pole in enumerate(poles_sorted):
    if i in used:
        continue
    # Find conjugate
    for j, other in enumerate(poles_sorted):
        if j in used or j == i:
            continue
        if abs(pole - other.conjugate()) < 1e-10:
            used.add(i); used.add(j)
            # Build biquad: (z - z1)(z - z1*) = z^2 - 2*Re(z1)*z + |z1|^2
            a1 = -2.0 * pole.real
            a2 = abs(pole) ** 2
            # Numerator: k_per_section * (z + 1)^2 = k_per_section*(z^2 + 2z + 1)
            b0 = k_per_section
            b1 = 2.0 * k_per_section
            b2 = k_per_section
            # Normalize by z^2: H(z) = (b0 + b1*z^-1 + b2*z^-2) / (1 + a1*z^-1 + a2*z^-2)
            sections.append((b0, b1, b2, a1, a2))
            break

print("/* Generated by tools/gen_filter_coefficients.py */")
print(f"/* fc={fc} Hz, fs={fs} Hz, 4th-order Butterworth */")
for i, (b0, b1, b2, a1, a2) in enumerate(sections, 1):
    dc = (b0 + b1 + b2) / (1 + a1 + a2)
    print(f"/* Section {i} — DC gain: {dc:.8f} (should be 1.0) */")
    print(f"#define LP4_S{i}_B0  {b0:.6e}f")
    print(f"#define LP4_S{i}_B1  {b1:.6e}f")
    print(f"#define LP4_S{i}_B2  {b2:.6e}f")
    print(f"#define LP4_S{i}_A1 ({a1:.8f}f)")
    print(f"#define LP4_S{i}_A2  {a2:.8f}f")
