#!/usr/bin/env python3
"""Generate 4th-order LP Butterworth coefficients, fc=1 Hz, fs=1000 Hz."""
from scipy.signal import butter
import numpy as np

sos = butter(4, 1.0 / (1000.0 / 2.0), btype='low', output='sos')
print("/* Generated by tools/gen_filter_coefficients.py */")
for i, (b0,b1,b2,a0,a1,a2) in enumerate(sos, 1):
    assert abs(a0 - 1.0) < 1e-10, "a0 must be 1"
    print(f"/* Section {i} */")
    print(f"#define LP4_S{i}_B0  {b0:.6e}f")
    print(f"#define LP4_S{i}_B1  {b1:.6e}f")
    print(f"#define LP4_S{i}_B2  {b2:.6e}f")
    print(f"#define LP4_S{i}_A1 ({a1:.8f}f)")
    print(f"#define LP4_S{i}_A2  {a2:.8f}f")

for i, (b0,b1,b2,a0,a1,a2) in enumerate(sos, 1):
    dc = (b0+b1+b2)/(1+a1+a2)
    print(f"/* Section {i} DC gain: {dc:.8f} (should be 1.0) */")
